### PR TITLE
* Feature: Added ability to run base_qos_init.py script multiple times * Update: Added schema for configuration file for base_qos_init.xml

### PR DESCRIPTION
**Pull request by hpersh**
Signed-off-by: Howard Persh <Howard_Persh@dell.com>

### CODE REVIEW

**Comment by theucke** [comment]
You’re missing a subject line in your commit message.

**Comment by jeff-yin** [comment]
@hpersh can you update your pull-request with this one minor change? We should be able to merge after this.

**Comment by hpersh** [comment]
Pull-request updated, HEAD is now f944b2894425d73be3b474c7203c07b9f834f2b9

**Comment by theucke** [comment]
Smoke test failed!

**Pull request closed without merging**
